<?php

namespace Database\Seeders;

use App\Models\Municipio;
use Illuminate\Database\Seeder;

class MunicipioSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    $municipios = [
                    "ACAPULCO DE JUÁREZ",
                    "ACATEPEC",
                    "AHUACUOTZINGO",
                    "AJUCHITLÁN DEL PROGRESO",
                    "ALCOZAUCA DE GUERRERO",
                    "ALPOYECA",
                    "APAXTLA",
                    "ARCELIA",
                    "ATENANGO DEL RÍO",
                    "ATLAMAJALCINGO DEL MONTE",
                    "ATLIXTAC",
                    "ATOYAC DE ÁLVAREZ",
                    "AYUTLA DE LOS LIBRES",
                    "AZOYÚ",
                    "BENITO JUÁREZ",
                    "BUENAVISTA DE CUÉLLAR",
                    "CHILAPA DE ÁLVAREZ",
                    "CHILPANCINGO DE LOS BRAVO",
                    "COAHUAYUTLA DE JOSÉ MARÍA IZAZAGA",
                    "COCHOAPA EL GRANDE",
                    "COCULA",
                    "COPALA",
                    "COPALILLO",
                    "COPANATOYAC",
                    "COYUCA DE BENÍTEZ",
                    "COYUCA DE CATALÁN",
                    "CUAJINICUILAPA",
                    "CUALÁC",
                    "CUAUTEPEC",
                    "CUETZALA DEL PROGRESO",
                    "CUTZAMALA DE PINZÓN",
                    "EDUARDO NERI",
                    "FLORENCIO VILLARREAL",
                    "GENERAL CANUTO A. NERI",
                    "GENERAL HELIODORO CASTILLO",
                    "HUAMUXTITLÁN",
                    "HUITZUCO DE LOS FIGUEROA",
                    "IGUALA DE LA INDEPENDENCIA",
                    "IGUALAPA",
                    "ILIATENCO",
                    "IXCATEOPAN DE CUAUHTÉMOC",
                    "JOSÉ JOAQUÍN DE HERRERA",
                    "JUAN R. ESCUDERO",
                    "JUCHITÁN",
                    "LA UNIÓN DE ISIDORO MONTES DE OCA",
                    "LEONARDO BRAVO",
                    "MALINALTEPEC",
                    "MARQUELIA",
                    "MÁRTIR DE CUILAPAN",
                    "METLATÓNOC",
                    "MOCHITLÁN",
                    "OLINALÁ",
                    "OMETEPEC",
                    "PEDRO ASCENCIO ALQUISIRAS",
                    "PETATLÁN",
                    "PILCAYA",
                    "PUNGARABATO",
                    "QUECHULTENANGO",
                    "SAN LUIS ACATLÁN",
                    "SAN MARCOS",
                    "SAN MIGUEL TOTOLAPAN",
                    "TAXCO DE ALARCÓN",
                    "TECOANAPA",
                    "TÉCPAN DE GALEANA",
                    "TELOLOAPAN",
                    "TEPECOACUILCO DE TRUJANO",
                    "TETIPAC",
                    "TIXTLA DE GUERRERO",
                    "TLACOACHISTLAHUACA",
                    "TLACOAPA",
                    "TLALCHAPA",
                    "TLALIXTAQUILLA DE MALDONADO",
                    "TLAPA DE COMONFORT",
                    "TLAPEHUALA",
                    "XALPATLÁHUAC",
                    "XOCHIHUEHUETLÁN",
                    "XOCHISTLAHUACA",
                    "ZAPOTITLÁN TABLAS",
                    "ZIHUATANEJO DE AZUETA",
                    "ZIRÁNDARO",
                    "ZITLALA",
              ];

    $delegaciones = [
                      "DA",
                      "DM",
                      "DC",
                      "DTC",
                      "DM",
                      "DM",
                      "DN",
                      "DTC",
                      "DN",
                      "DM",
                      "DM",
                      "DCG",
                      "CCH",
                      "CCH",
                      "DCG",
                      "DN",
                      "DC",
                      "DC",
                      "DCG",
                      "DM",
                      "DN",
                      "CCH",
                      "DN",
                      "DM",
                      "DCG",
                      "DTC",
                      "CCH",
                      "DM",
                      "CCH",
                      "DN",
                      "DTC",
                      "DC",
                      "CCH",
                      "DN",
                      "DC",
                      "DM",
                      "DN",
                      "DN",
                      "CCH",
                      "DM",
                      "DN",
                      "DC",
                      "DC",
                      "CCH",
                      "DCG",
                      "DC",
                      "DM",
                      "CCH",
                      "DC",
                      "DM",
                      "DC",
                      "DM",
                      "DCC",
                      "DN",
                      "DCG",
                      "DN",
                      "DTC",
                      "DC",
                      "DCC",
                      "DCC",
                      "DTC",
                      "DN",
                      "DCC",
                      "DCG",
                      "DN",
                      "DN",
                      "DN",
                      "DC",
                      "DCC",
                      "DM",
                      "DTC",
                      "DM",
                      "DM",
                      "DTC",
                      "DM",
                      "DM",
                      "DCC",
                      "DM",
                      "DCG",
                      "DTC",
                      "DC",
            ];

      for ($item=0; $item < count($municipios); $item++) {
        foreach ($municipios as $municipio) {
            $municipio = new Municipio;
            $municipio->NombreMunicipio = $municipios[$item];
            $municipio->Delegacion = $delegaciones[$item];
          }       
          $municipio->save(); 
        }
  }
}

